#!/usr/bin/env bash
# Pings an IP address passed as an argument.

# Accepts a string as an argument.
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no,
#+                argument passed.
# Ping the IP 5 times.

if [ "$#" -lt "1" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    # exit with staus code 1
    exit 1
else
    ping "$1" -c 5
fi
